// Code generated by mockery v2.46.3. DO NOT EDIT.

package directoryReader

import mock "github.com/stretchr/testify/mock"

// MockDirectoryReader is an autogenerated mock type for the DirectoryReader type
type MockDirectoryReader struct {
	mock.Mock
}

// GetFoldersInDirectory provides a mock function with given fields: dirPath
func (_m *MockDirectoryReader) GetFoldersInDirectory(dirPath string) ([]string, error) {
	ret := _m.Called(dirPath)

	if len(ret) == 0 {
		panic("no return value specified for GetFoldersInDirectory")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(dirPath)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(dirPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dirPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDirectoryReader creates a new instance of MockDirectoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectoryReader {
	mock := &MockDirectoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
