// Code generated by mockery v2.53.3. DO NOT EDIT.

package adapters

import mock "github.com/stretchr/testify/mock"

// MockGitAdapter is an autogenerated mock type for the GitAdapter type
type MockGitAdapter struct {
	mock.Mock
}

type MockGitAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitAdapter) EXPECT() *MockGitAdapter_Expecter {
	return &MockGitAdapter_Expecter{mock: &_m.Mock}
}

// AddWorktree provides a mock function with given fields: params
func (_m *MockGitAdapter) AddWorktree(params AddWorktreeConfig) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for AddWorktree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(AddWorktreeConfig) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_AddWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorktree'
type MockGitAdapter_AddWorktree_Call struct {
	*mock.Call
}

// AddWorktree is a helper method to define mock.On call
//   - params AddWorktreeConfig
func (_e *MockGitAdapter_Expecter) AddWorktree(params interface{}) *MockGitAdapter_AddWorktree_Call {
	return &MockGitAdapter_AddWorktree_Call{Call: _e.mock.On("AddWorktree", params)}
}

func (_c *MockGitAdapter_AddWorktree_Call) Run(run func(params AddWorktreeConfig)) *MockGitAdapter_AddWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(AddWorktreeConfig))
	})
	return _c
}

func (_c *MockGitAdapter_AddWorktree_Call) Return(_a0 error) *MockGitAdapter_AddWorktree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_AddWorktree_Call) RunAndReturn(run func(AddWorktreeConfig) error) *MockGitAdapter_AddWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// CloneBare provides a mock function with given fields: _a0, _a1
func (_m *MockGitAdapter) CloneBare(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CloneBare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_CloneBare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneBare'
type MockGitAdapter_CloneBare_Call struct {
	*mock.Call
}

// CloneBare is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *MockGitAdapter_Expecter) CloneBare(_a0 interface{}, _a1 interface{}) *MockGitAdapter_CloneBare_Call {
	return &MockGitAdapter_CloneBare_Call{Call: _e.mock.On("CloneBare", _a0, _a1)}
}

func (_c *MockGitAdapter_CloneBare_Call) Run(run func(_a0 string, _a1 string)) *MockGitAdapter_CloneBare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGitAdapter_CloneBare_Call) Return(_a0 error) *MockGitAdapter_CloneBare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_CloneBare_Call) RunAndReturn(run func(string, string) error) *MockGitAdapter_CloneBare_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigureGitBare provides a mock function with given fields: path
func (_m *MockGitAdapter) ConfigureGitBare(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureGitBare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_ConfigureGitBare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureGitBare'
type MockGitAdapter_ConfigureGitBare_Call struct {
	*mock.Call
}

// ConfigureGitBare is a helper method to define mock.On call
//   - path string
func (_e *MockGitAdapter_Expecter) ConfigureGitBare(path interface{}) *MockGitAdapter_ConfigureGitBare_Call {
	return &MockGitAdapter_ConfigureGitBare_Call{Call: _e.mock.On("ConfigureGitBare", path)}
}

func (_c *MockGitAdapter_ConfigureGitBare_Call) Run(run func(path string)) *MockGitAdapter_ConfigureGitBare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitAdapter_ConfigureGitBare_Call) Return(_a0 error) *MockGitAdapter_ConfigureGitBare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_ConfigureGitBare_Call) RunAndReturn(run func(string) error) *MockGitAdapter_ConfigureGitBare_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranch provides a mock function with given fields: branch, path, forceDelete
func (_m *MockGitAdapter) DeleteBranch(branch string, path string, forceDelete bool) error {
	ret := _m.Called(branch, path, forceDelete)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(branch, path, forceDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_DeleteBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranch'
type MockGitAdapter_DeleteBranch_Call struct {
	*mock.Call
}

// DeleteBranch is a helper method to define mock.On call
//   - branch string
//   - path string
//   - forceDelete bool
func (_e *MockGitAdapter_Expecter) DeleteBranch(branch interface{}, path interface{}, forceDelete interface{}) *MockGitAdapter_DeleteBranch_Call {
	return &MockGitAdapter_DeleteBranch_Call{Call: _e.mock.On("DeleteBranch", branch, path, forceDelete)}
}

func (_c *MockGitAdapter_DeleteBranch_Call) Run(run func(branch string, path string, forceDelete bool)) *MockGitAdapter_DeleteBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockGitAdapter_DeleteBranch_Call) Return(_a0 error) *MockGitAdapter_DeleteBranch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_DeleteBranch_Call) RunAndReturn(run func(string, string, bool) error) *MockGitAdapter_DeleteBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranchRef provides a mock function with given fields: branch, path
func (_m *MockGitAdapter) DeleteBranchRef(branch string, path string) error {
	ret := _m.Called(branch, path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranchRef")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(branch, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_DeleteBranchRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranchRef'
type MockGitAdapter_DeleteBranchRef_Call struct {
	*mock.Call
}

// DeleteBranchRef is a helper method to define mock.On call
//   - branch string
//   - path string
func (_e *MockGitAdapter_Expecter) DeleteBranchRef(branch interface{}, path interface{}) *MockGitAdapter_DeleteBranchRef_Call {
	return &MockGitAdapter_DeleteBranchRef_Call{Call: _e.mock.On("DeleteBranchRef", branch, path)}
}

func (_c *MockGitAdapter_DeleteBranchRef_Call) Run(run func(branch string, path string)) *MockGitAdapter_DeleteBranchRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGitAdapter_DeleteBranchRef_Call) Return(_a0 error) *MockGitAdapter_DeleteBranchRef_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_DeleteBranchRef_Call) RunAndReturn(run func(string, string) error) *MockGitAdapter_DeleteBranchRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetBareRepoPath provides a mock function with no fields
func (_m *MockGitAdapter) GetBareRepoPath() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBareRepoPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetBareRepoPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBareRepoPath'
type MockGitAdapter_GetBareRepoPath_Call struct {
	*mock.Call
}

// GetBareRepoPath is a helper method to define mock.On call
func (_e *MockGitAdapter_Expecter) GetBareRepoPath() *MockGitAdapter_GetBareRepoPath_Call {
	return &MockGitAdapter_GetBareRepoPath_Call{Call: _e.mock.On("GetBareRepoPath")}
}

func (_c *MockGitAdapter_GetBareRepoPath_Call) Run(run func()) *MockGitAdapter_GetBareRepoPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitAdapter_GetBareRepoPath_Call) Return(_a0 string, _a1 error) *MockGitAdapter_GetBareRepoPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetBareRepoPath_Call) RunAndReturn(run func() (string, error)) *MockGitAdapter_GetBareRepoPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalBranches provides a mock function with given fields: _a0
func (_m *MockGitAdapter) GetLocalBranches(_a0 *string) ([]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLocalBranches")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*string) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetLocalBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalBranches'
type MockGitAdapter_GetLocalBranches_Call struct {
	*mock.Call
}

// GetLocalBranches is a helper method to define mock.On call
//   - _a0 *string
func (_e *MockGitAdapter_Expecter) GetLocalBranches(_a0 interface{}) *MockGitAdapter_GetLocalBranches_Call {
	return &MockGitAdapter_GetLocalBranches_Call{Call: _e.mock.On("GetLocalBranches", _a0)}
}

func (_c *MockGitAdapter_GetLocalBranches_Call) Run(run func(_a0 *string)) *MockGitAdapter_GetLocalBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*string))
	})
	return _c
}

func (_c *MockGitAdapter_GetLocalBranches_Call) Return(_a0 []string, _a1 error) *MockGitAdapter_GetLocalBranches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetLocalBranches_Call) RunAndReturn(run func(*string) ([]string, error)) *MockGitAdapter_GetLocalBranches_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectName provides a mock function with no fields
func (_m *MockGitAdapter) GetProjectName() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProjectName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetProjectName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectName'
type MockGitAdapter_GetProjectName_Call struct {
	*mock.Call
}

// GetProjectName is a helper method to define mock.On call
func (_e *MockGitAdapter_Expecter) GetProjectName() *MockGitAdapter_GetProjectName_Call {
	return &MockGitAdapter_GetProjectName_Call{Call: _e.mock.On("GetProjectName")}
}

func (_c *MockGitAdapter_GetProjectName_Call) Run(run func()) *MockGitAdapter_GetProjectName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitAdapter_GetProjectName_Call) Return(_a0 string, _a1 error) *MockGitAdapter_GetProjectName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetProjectName_Call) RunAndReturn(run func() (string, error)) *MockGitAdapter_GetProjectName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteBranches provides a mock function with given fields: _a0
func (_m *MockGitAdapter) GetRemoteBranches(_a0 *string) ([]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteBranches")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*string) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetRemoteBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteBranches'
type MockGitAdapter_GetRemoteBranches_Call struct {
	*mock.Call
}

// GetRemoteBranches is a helper method to define mock.On call
//   - _a0 *string
func (_e *MockGitAdapter_Expecter) GetRemoteBranches(_a0 interface{}) *MockGitAdapter_GetRemoteBranches_Call {
	return &MockGitAdapter_GetRemoteBranches_Call{Call: _e.mock.On("GetRemoteBranches", _a0)}
}

func (_c *MockGitAdapter_GetRemoteBranches_Call) Run(run func(_a0 *string)) *MockGitAdapter_GetRemoteBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*string))
	})
	return _c
}

func (_c *MockGitAdapter_GetRemoteBranches_Call) Return(_a0 []string, _a1 error) *MockGitAdapter_GetRemoteBranches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetRemoteBranches_Call) RunAndReturn(run func(*string) ([]string, error)) *MockGitAdapter_GetRemoteBranches_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoName provides a mock function with given fields: path
func (_m *MockGitAdapter) GetRepoName(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetRepoName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoName'
type MockGitAdapter_GetRepoName_Call struct {
	*mock.Call
}

// GetRepoName is a helper method to define mock.On call
//   - path string
func (_e *MockGitAdapter_Expecter) GetRepoName(path interface{}) *MockGitAdapter_GetRepoName_Call {
	return &MockGitAdapter_GetRepoName_Call{Call: _e.mock.On("GetRepoName", path)}
}

func (_c *MockGitAdapter_GetRepoName_Call) Run(run func(path string)) *MockGitAdapter_GetRepoName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGitAdapter_GetRepoName_Call) Return(_a0 string, _a1 error) *MockGitAdapter_GetRepoName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetRepoName_Call) RunAndReturn(run func(string) (string, error)) *MockGitAdapter_GetRepoName_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorktrees provides a mock function with given fields: path
func (_m *MockGitAdapter) GetWorktrees(path *string) ([]string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetWorktrees")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) ([]string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(*string) []string); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitAdapter_GetWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorktrees'
type MockGitAdapter_GetWorktrees_Call struct {
	*mock.Call
}

// GetWorktrees is a helper method to define mock.On call
//   - path *string
func (_e *MockGitAdapter_Expecter) GetWorktrees(path interface{}) *MockGitAdapter_GetWorktrees_Call {
	return &MockGitAdapter_GetWorktrees_Call{Call: _e.mock.On("GetWorktrees", path)}
}

func (_c *MockGitAdapter_GetWorktrees_Call) Run(run func(path *string)) *MockGitAdapter_GetWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*string))
	})
	return _c
}

func (_c *MockGitAdapter_GetWorktrees_Call) Return(_a0 []string, _a1 error) *MockGitAdapter_GetWorktrees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitAdapter_GetWorktrees_Call) RunAndReturn(run func(*string) ([]string, error)) *MockGitAdapter_GetWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorktree provides a mock function with given fields: worktreeName, path, forceDelete
func (_m *MockGitAdapter) RemoveWorktree(worktreeName string, path *string, forceDelete bool) error {
	ret := _m.Called(worktreeName, path, forceDelete)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorktree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *string, bool) error); ok {
		r0 = rf(worktreeName, path, forceDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGitAdapter_RemoveWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorktree'
type MockGitAdapter_RemoveWorktree_Call struct {
	*mock.Call
}

// RemoveWorktree is a helper method to define mock.On call
//   - worktreeName string
//   - path *string
//   - forceDelete bool
func (_e *MockGitAdapter_Expecter) RemoveWorktree(worktreeName interface{}, path interface{}, forceDelete interface{}) *MockGitAdapter_RemoveWorktree_Call {
	return &MockGitAdapter_RemoveWorktree_Call{Call: _e.mock.On("RemoveWorktree", worktreeName, path, forceDelete)}
}

func (_c *MockGitAdapter_RemoveWorktree_Call) Run(run func(worktreeName string, path *string, forceDelete bool)) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*string), args[2].(bool))
	})
	return _c
}

func (_c *MockGitAdapter_RemoveWorktree_Call) Return(_a0 error) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitAdapter_RemoveWorktree_Call) RunAndReturn(run func(string, *string, bool) error) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitAdapter creates a new instance of MockGitAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitAdapter {
	mock := &MockGitAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
