// Code generated by mockery v2.46.3. DO NOT EDIT.

package form

import mock "github.com/stretchr/testify/mock"

// MockHuhForm is an autogenerated mock type for the FormInterface type
type MockHuhForm struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *MockHuhForm) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOptions provides a mock function with given fields: stringOptions
func (_m *MockHuhForm) SetOptions(stringOptions []string) {
	_m.Called(stringOptions)
}

// SetSelections provides a mock function with given fields: selections
func (_m *MockHuhForm) SetSelections(selections *[]string) {
	_m.Called(selections)
}

// NewMockHuhForm creates a new instance of MockHuhForm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHuhForm(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHuhForm {
	mock := &MockHuhForm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
