// Code generated by mockery v2.53.3. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// GetDefaultConfig provides a mock function with given fields: bareRepoPath, projectName
func (_m *MockConfig) GetDefaultConfig(bareRepoPath string, projectName string) (AppConfig, error) {
	ret := _m.Called(bareRepoPath, projectName)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultConfig")
	}

	var r0 AppConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (AppConfig, error)); ok {
		return rf(bareRepoPath, projectName)
	}
	if rf, ok := ret.Get(0).(func(string, string) AppConfig); ok {
		r0 = rf(bareRepoPath, projectName)
	} else {
		r0 = ret.Get(0).(AppConfig)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bareRepoPath, projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_GetDefaultConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultConfig'
type MockConfig_GetDefaultConfig_Call struct {
	*mock.Call
}

// GetDefaultConfig is a helper method to define mock.On call
//   - bareRepoPath string
//   - projectName string
func (_e *MockConfig_Expecter) GetDefaultConfig(bareRepoPath interface{}, projectName interface{}) *MockConfig_GetDefaultConfig_Call {
	return &MockConfig_GetDefaultConfig_Call{Call: _e.mock.On("GetDefaultConfig", bareRepoPath, projectName)}
}

func (_c *MockConfig_GetDefaultConfig_Call) Run(run func(bareRepoPath string, projectName string)) *MockConfig_GetDefaultConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockConfig_GetDefaultConfig_Call) Return(_a0 AppConfig, _a1 error) *MockConfig_GetDefaultConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_GetDefaultConfig_Call) RunAndReturn(run func(string, string) (AppConfig, error)) *MockConfig_GetDefaultConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ImportYamlConfigFile provides a mock function with given fields: cfg
func (_m *MockConfig) ImportYamlConfigFile(cfg AppConfig) (AppConfig, error) {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for ImportYamlConfigFile")
	}

	var r0 AppConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(AppConfig) (AppConfig, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(AppConfig) AppConfig); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Get(0).(AppConfig)
	}

	if rf, ok := ret.Get(1).(func(AppConfig) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfig_ImportYamlConfigFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportYamlConfigFile'
type MockConfig_ImportYamlConfigFile_Call struct {
	*mock.Call
}

// ImportYamlConfigFile is a helper method to define mock.On call
//   - cfg AppConfig
func (_e *MockConfig_Expecter) ImportYamlConfigFile(cfg interface{}) *MockConfig_ImportYamlConfigFile_Call {
	return &MockConfig_ImportYamlConfigFile_Call{Call: _e.mock.On("ImportYamlConfigFile", cfg)}
}

func (_c *MockConfig_ImportYamlConfigFile_Call) Run(run func(cfg AppConfig)) *MockConfig_ImportYamlConfigFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(AppConfig))
	})
	return _c
}

func (_c *MockConfig_ImportYamlConfigFile_Call) Return(_a0 AppConfig, _a1 error) *MockConfig_ImportYamlConfigFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfig_ImportYamlConfigFile_Call) RunAndReturn(run func(AppConfig) (AppConfig, error)) *MockConfig_ImportYamlConfigFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
