// Code generated by mockery v2.53.3. DO NOT EDIT.

package confirmer

import mock "github.com/stretchr/testify/mock"

// MockConfirmer is an autogenerated mock type for the Confirmer type
type MockConfirmer struct {
	mock.Mock
}

type MockConfirmer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfirmer) EXPECT() *MockConfirmer_Expecter {
	return &MockConfirmer_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function with given fields: message
func (_m *MockConfirmer) Confirm(message string) (bool, error) {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(message)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfirmer_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockConfirmer_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - message string
func (_e *MockConfirmer_Expecter) Confirm(message interface{}) *MockConfirmer_Confirm_Call {
	return &MockConfirmer_Confirm_Call{Call: _e.mock.On("Confirm", message)}
}

func (_c *MockConfirmer_Confirm_Call) Run(run func(message string)) *MockConfirmer_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfirmer_Confirm_Call) Return(_a0 bool, _a1 error) *MockConfirmer_Confirm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfirmer_Confirm_Call) RunAndReturn(run func(string) (bool, error)) *MockConfirmer_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfirmer creates a new instance of MockConfirmer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfirmer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfirmer {
	mock := &MockConfirmer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
