// Code generated by mockery v2.53.3. DO NOT EDIT.

package connector

import (
	"github.com/garrettkrohn/treekanga/models"
	mock "github.com/stretchr/testify/mock"
)

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

type MockConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnector) EXPECT() *MockConnector_Expecter {
	return &MockConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: name, opts
func (_m *MockConnector) Connect(name string, opts models.ConnectOpts) error {
	ret := _m.Called(name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, models.ConnectOpts) error); ok {
		r0 = rf(name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - name string
//   - opts models.ConnectOpts
func (_e *MockConnector_Expecter) Connect(name interface{}, opts interface{}) *MockConnector_Connect_Call {
	return &MockConnector_Connect_Call{Call: _e.mock.On("Connect", name, opts)}
}

func (_c *MockConnector_Connect_Call) Run(run func(name string, opts models.ConnectOpts)) *MockConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.ConnectOpts))
	})
	return _c
}

func (_c *MockConnector_Connect_Call) Return(_a0 error) *MockConnector_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnector_Connect_Call) RunAndReturn(run func(string, models.ConnectOpts) error) *MockConnector_Connect_Call {
	_c.Run(func(name string, opts models.ConnectOpts) {
		run(name, opts)
	})
	return _c
}

// CursorConnect provides a mock function with given fields: newRootPath
func (_m *MockConnector) CursorConnect(newRootPath string) {
	_m.Called(newRootPath)
}

// MockConnector_CursorConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CursorConnect'
type MockConnector_CursorConnect_Call struct {
	*mock.Call
}

// CursorConnect is a helper method to define mock.On call
//   - newRootPath string
func (_e *MockConnector_Expecter) CursorConnect(newRootPath interface{}) *MockConnector_CursorConnect_Call {
	return &MockConnector_CursorConnect_Call{Call: _e.mock.On("CursorConnect", newRootPath)}
}

func (_c *MockConnector_CursorConnect_Call) Run(run func(newRootPath string)) *MockConnector_CursorConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConnector_CursorConnect_Call) Return() *MockConnector_CursorConnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnector_CursorConnect_Call) RunAndReturn(run func(string)) *MockConnector_CursorConnect_Call {
	_c.Run(run)
	return _c
}

// VsCodeConnect provides a mock function with given fields: newRootPath
func (_m *MockConnector) VsCodeConnect(newRootPath string) {
	_m.Called(newRootPath)
}

// MockConnector_VsCodeConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VsCodeConnect'
type MockConnector_VsCodeConnect_Call struct {
	*mock.Call
}

// VsCodeConnect is a helper method to define mock.On call
//   - newRootPath string
func (_e *MockConnector_Expecter) VsCodeConnect(newRootPath interface{}) *MockConnector_VsCodeConnect_Call {
	return &MockConnector_VsCodeConnect_Call{Call: _e.mock.On("VsCodeConnect", newRootPath)}
}

func (_c *MockConnector_VsCodeConnect_Call) Run(run func(newRootPath string)) *MockConnector_VsCodeConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConnector_VsCodeConnect_Call) Return() *MockConnector_VsCodeConnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConnector_VsCodeConnect_Call) RunAndReturn(run func(string)) *MockConnector_VsCodeConnect_Call {
	_c.Run(run)
	return _c
}

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
